package com.github.rakhmedovrs.protocolbuffer3.bacics_part_1.java;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <pre>
     * represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    com.google.protobuf.ByteString getSmallPicture();

    /**
     * <code>bool is_profile_verified = 5;</code>
     * @return The isProfileVerified.
     */
    boolean getIsProfileVerified();

    /**
     * <pre>
     * height in centimeters
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    float getHeight();

    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    java.util.List<java.lang.String>
        getPhoneNumbersList();
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    int getPhoneNumbersCount();
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    java.lang.String getPhoneNumbers(int index);
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index);

    /**
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The enum numeric value on the wire for eyeColour.
     */
    int getEyeColourValue();
    /**
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The eyeColour.
     */
    Enums.Person.EyeColour getEyeColour();
  }
  /**
   * <pre>
   *Person is used to identify users
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColour_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {

              smallPicture_ = input.readBytes();
              break;
            }
            case 40: {

              isProfileVerified_ = input.readBool();
              break;
            }
            case 53: {

              height_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phoneNumbers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneNumbers_.add(s);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              eyeColour_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Enums.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Enums.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Enums.Person.class, Enums.Person.Builder.class);
    }

    /**
     * <pre>
     * only 3 eye colours supported
     * </pre>
     *
     * Protobuf enum {@code Person.EyeColour}
     */
    public enum EyeColour
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>GREEN = 1;</code>
       */
      GREEN(1),
      /**
       * <code>BROWN = 2;</code>
       */
      BROWN(2),
      /**
       * <code>BLUE = 3;</code>
       */
      BLUE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>GREEN = 1;</code>
       */
      public static final int GREEN_VALUE = 1;
      /**
       * <code>BROWN = 2;</code>
       */
      public static final int BROWN_VALUE = 2;
      /**
       * <code>BLUE = 3;</code>
       */
      public static final int BLUE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EyeColour valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EyeColour forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return GREEN;
          case 2: return BROWN;
          case 3: return BLUE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EyeColour>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EyeColour> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EyeColour>() {
              public EyeColour findValueByNumber(int number) {
                return EyeColour.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Enums.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final EyeColour[] VALUES = values();

      public static EyeColour valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EyeColour(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.EyeColour)
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMALL_PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString smallPicture_;
    /**
     * <pre>
     * represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSmallPicture() {
      return smallPicture_;
    }

    public static final int IS_PROFILE_VERIFIED_FIELD_NUMBER = 5;
    private boolean isProfileVerified_;
    /**
     * <code>bool is_profile_verified = 5;</code>
     * @return The isProfileVerified.
     */
    @java.lang.Override
    public boolean getIsProfileVerified() {
      return isProfileVerified_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private float height_;
    /**
     * <pre>
     * height in centimeters
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public float getHeight() {
      return height_;
    }

    public static final int PHONE_NUMBERS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList phoneNumbers_;
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneNumbersList() {
      return phoneNumbers_;
    }
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    public java.lang.String getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <pre>
     * optional list of provided phone numbers
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    public com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index) {
      return phoneNumbers_.getByteString(index);
    }

    public static final int EYE_COLOUR_FIELD_NUMBER = 8;
    private int eyeColour_;
    /**
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The enum numeric value on the wire for eyeColour.
     */
    @java.lang.Override public int getEyeColourValue() {
      return eyeColour_;
    }
    /**
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The eyeColour.
     */
    @java.lang.Override public Enums.Person.EyeColour getEyeColour() {
      @SuppressWarnings("deprecation")
      Enums.Person.EyeColour result = Enums.Person.EyeColour.valueOf(eyeColour_);
      return result == null ? Enums.Person.EyeColour.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        output.writeBytes(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        output.writeBool(5, isProfileVerified_);
      }
      if (java.lang.Float.floatToRawIntBits(height_) != 0) {
        output.writeFloat(6, height_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phoneNumbers_.getRaw(i));
      }
      if (eyeColour_ != Enums.Person.EyeColour.UNKNOWN.getNumber()) {
        output.writeEnum(8, eyeColour_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isProfileVerified_);
      }
      if (java.lang.Float.floatToRawIntBits(height_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phoneNumbers_.size(); i++) {
          dataSize += computeStringSizeNoTag(phoneNumbers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhoneNumbersList().size();
      }
      if (eyeColour_ != Enums.Person.EyeColour.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, eyeColour_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Enums.Person)) {
        return super.equals(obj);
      }
      Enums.Person other = (Enums.Person) obj;

      if (getAge()
          != other.getAge()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getSmallPicture()
          .equals(other.getSmallPicture())) return false;
      if (getIsProfileVerified()
          != other.getIsProfileVerified()) return false;
      if (java.lang.Float.floatToIntBits(getHeight())
          != java.lang.Float.floatToIntBits(
              other.getHeight())) return false;
      if (!getPhoneNumbersList()
          .equals(other.getPhoneNumbersList())) return false;
      if (eyeColour_ != other.eyeColour_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SMALL_PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSmallPicture().hashCode();
      hash = (37 * hash) + IS_PROFILE_VERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsProfileVerified());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhoneNumbersCount() > 0) {
        hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumbersList().hashCode();
      }
      hash = (37 * hash) + EYE_COLOUR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColour_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Enums.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Enums.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Enums.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Enums.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Enums.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Enums.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Enums.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Enums.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Enums.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Enums.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Enums.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Enums.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Enums.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Person is used to identify users
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        Enums.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Enums.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Enums.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Enums.Person.class, Enums.Person.Builder.class);
      }

      // Construct using Enums.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        age_ = 0;

        firstName_ = "";

        lastName_ = "";

        smallPicture_ = com.google.protobuf.ByteString.EMPTY;

        isProfileVerified_ = false;

        height_ = 0F;

        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        eyeColour_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Enums.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public Enums.Person getDefaultInstanceForType() {
        return Enums.Person.getDefaultInstance();
      }

      @java.lang.Override
      public Enums.Person build() {
        Enums.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Enums.Person buildPartial() {
        Enums.Person result = new Enums.Person(this);
        int from_bitField0_ = bitField0_;
        result.age_ = age_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.smallPicture_ = smallPicture_;
        result.isProfileVerified_ = isProfileVerified_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phoneNumbers_ = phoneNumbers_;
        result.eyeColour_ = eyeColour_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Enums.Person) {
          return mergeFrom((Enums.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Enums.Person other) {
        if (other == Enums.Person.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getSmallPicture() != com.google.protobuf.ByteString.EMPTY) {
          setSmallPicture(other.getSmallPicture());
        }
        if (other.getIsProfileVerified() != false) {
          setIsProfileVerified(other.getIsProfileVerified());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
        if (other.eyeColour_ != 0) {
          setEyeColourValue(other.getEyeColourValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Enums.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Enums.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return The smallPicture.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSmallPicture() {
        return smallPicture_;
      }
      /**
       * <pre>
       * represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @param value The smallPicture to set.
       * @return This builder for chaining.
       */
      public Builder setSmallPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        smallPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSmallPicture() {
        
        smallPicture_ = getDefaultInstance().getSmallPicture();
        onChanged();
        return this;
      }

      private boolean isProfileVerified_ ;
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @return The isProfileVerified.
       */
      @java.lang.Override
      public boolean getIsProfileVerified() {
        return isProfileVerified_;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @param value The isProfileVerified to set.
       * @return This builder for chaining.
       */
      public Builder setIsProfileVerified(boolean value) {
        
        isProfileVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsProfileVerified() {
        
        isProfileVerified_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <pre>
       * height in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return The height.
       */
      @java.lang.Override
      public float getHeight() {
        return height_;
      }
      /**
       * <pre>
       * height in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = new com.google.protobuf.LazyStringArrayList(phoneNumbers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return A list containing the phoneNumbers.
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneNumbersList() {
        return phoneNumbers_.getUnmodifiableView();
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return The count of phoneNumbers.
       */
      public int getPhoneNumbersCount() {
        return phoneNumbers_.size();
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the element to return.
       * @return The phoneNumbers at the given index.
       */
      public java.lang.String getPhoneNumbers(int index) {
        return phoneNumbers_.get(index);
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phoneNumbers at the given index.
       */
      public com.google.protobuf.ByteString
          getPhoneNumbersBytes(int index) {
        return phoneNumbers_.getByteString(index);
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index to set the value at.
       * @param value The phoneNumbers to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumbers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param values The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhoneNumbers(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumbers() {
        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional list of provided phone numbers
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The bytes of the phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }

      private int eyeColour_ = 0;
      /**
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return The enum numeric value on the wire for eyeColour.
       */
      @java.lang.Override public int getEyeColourValue() {
        return eyeColour_;
      }
      /**
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @param value The enum numeric value on the wire for eyeColour to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColourValue(int value) {
        
        eyeColour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return The eyeColour.
       */
      @java.lang.Override
      public Enums.Person.EyeColour getEyeColour() {
        @SuppressWarnings("deprecation")
        Enums.Person.EyeColour result = Enums.Person.EyeColour.valueOf(eyeColour_);
        return result == null ? Enums.Person.EyeColour.UNRECOGNIZED : result;
      }
      /**
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @param value The eyeColour to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColour(Enums.Person.EyeColour value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColour_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEyeColour() {
        
        eyeColour_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final Enums.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Enums.Person();
    }

    public static Enums.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Enums.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto\"\370\001\n\006Person\022\013\n\003age\030\001 \001(\005\022\022\n" +
      "\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\025\n\r" +
      "small_picture\030\004 \001(\014\022\033\n\023is_profile_verifi" +
      "ed\030\005 \001(\010\022\016\n\006height\030\006 \001(\002\022\025\n\rphone_number" +
      "s\030\007 \003(\t\022%\n\neye_colour\030\010 \001(\0162\021.Person.Eye" +
      "Colour\"8\n\tEyeColour\022\013\n\007UNKNOWN\020\000\022\t\n\005GREE" +
      "N\020\001\022\t\n\005BROWN\020\002\022\010\n\004BLUE\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "SmallPicture", "IsProfileVerified", "Height", "PhoneNumbers", "EyeColour", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
